 



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template and will be re-created if deleted
//	   with default implementation.
// </auto-generated>
//------------------------------------------------------------------------------
using MyProject.Interface.Infrastructure;
using System.Data.Entity;
namespace MyProject.Interface.Infrastructure
{

    /// <summary>
    /// MyProject implementation of Unit of Work
    /// </summary>
	public partial interface IMyProjectUnitOfWork
		: IUnitOfWork
	{
					
		/// <summary>
		/// Gets the BookRepository repository.
		/// </summary>
		/// <value>
		/// The BookRepository repository.
		/// </value>
        MyProject.Interface.Repository.IBookRepository BookRepository { get; }
				
    }
}