 



namespace MyProject.Interface.Repository
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated from a template and will be re-created if deleted
    //	   with default values if executed.
    // </auto-generated>
    //------------------------------------------------------------------------------
    using MyProject.Model.DataModel;
    using System;

    /// <summary>
    /// Interface to interact with <see cref="MyProject.Model.DataModel.Book"/> domain model.
    /// </summary>
    public partial interface IBookRepository
	    : IRepository<Book>
    {


    }
}
