
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template and will be re-created if deleted
//	   with default implementation.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyProject.Interface.Repository
{
    using MyProject.Model.DataModel;
    using System;

    /// <summary>
    /// Interface to interact with <see cref="MyProject.Model.DataModel.Book"/> domain model.
    /// </summary>
    public partial interface IBookRepository
	    : IRepository<Book>
    {
    }
}
