 



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template and will be re-created if deleted
//	   with default implementation.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.Extensions.DependencyInjection;
namespace MyProject.DB.Infrastructure.Configuration
{

    /// <summary>
    /// Registration of repository with Dependency Injection.
    /// </summary>
	public static class ExtensionUnitOfWorkService
	{
        /// <summary>
        /// Registers the repositories.
        /// </summary>
        /// <param name="service">The service collection.</param>
		public static void RegisterRepositories(this IServiceCollection service)
		{
			service.AddScoped<MyProject.Interface.Repository.IBookRepository, MyProject.DB.Repository.BookRepository>();
		}
	}
}